"""Constants module."""

PREMIS_ADDRESS = "info:lc/xmlns/premis-v2"
EVENT_DIGEST = "message digest calculation"
EVENT_CHANGE = "filename change"
EVENT_CONVERSION = "conversion"
EVENT_CREATION = "information package creation"
EVENT_MODIFICATION = "modification"
EVENT_META_MODIFICATION = "metadata modification"
EVENT_NORMALIZATION = "normalization"
EVENT_MIGRATION = "migration"
EVENT_FORENSIC = "forensic feature analysis"

FILE_OUTCOME_SOURCE = "source"
FILE_USE_IGNORE_VALIDATION = "fi-dpres-ignore-validation-errors"
FILE_USE_NO_VALIDATION = "fi-dpres-no-file-format-validation"
