[organization]
# Give your organization information below.
# - name is your organization name, this will appear in METS.
# - contract is your contract ID, this will appear in METS.
# - sign_key is the key to sign your SIP.
# For example:
# name=Organization X
# contract=urn:uuid:474418c5-79a6-4e86-bfc8-5aed0a3337d7
# sign_key=/path/to/sign.key
name=
contract=
sign_key=

[script]
# Change the following only if needed:
# - desc_metadata_format is the descriptive metadata standard
# - desc_metadata_version is the version of the descriptive metadata standard
# - desc_metadata_source_format is either "string" or "file"
adaptor=postalmuseum
desc_metadata_format=LIDO
desc_metadata_version=1.1
desc_metadata_source_format=string
